### PR TITLE
README maintenance

### PR DESCRIPTION
**Pull request by tanho63**
more visually indicate missing slides, reorder folder descs to move presentations up, add links to git workflow videos

### CODE REVIEW

**Comment by tanho63** [comment]
I think a number of these weeks got combined into one presentation, and are listed by chapter instead. Wonder if we should either a) edit videostamps so that it's hitting by chapter or b) reorg listing so that it's one entry per week. `b` is more consistent with AdvR and planned rpkg clubs, `a` is more useful for others reading down the line? @jonthegeek

**Review by jonthegeek — DISMISSED** [review]
I think we should probably organize things the way the club organizes them, but that can be weird if different clubs use different groupings. I can't think of a good answer but editing or timestamping videos is hard.

**Comment by tanho63** [comment]
Adding a seconds param to jump a video ahead might be okay to do

**Comment by jonthegeek** [comment]
It feels fragile. It might be the best solution, but there are likely times when two chapters will be discussed more merged-together than a jump would allow.

Maybe go by chapter but specifically note when they're combined, and link to the same video from both (with or without a s param)?

**Review by jonthegeek — APPROVED** [review]
I think this is a good solution!

**Pull request merged**
