### PR TITLE
Adding presentation slides and exercise answers for visualisations chapter

### PR DESCRIPTION
**Pull request by camcaan**

### CODE REVIEW

**Review by tanho63 — CHANGES_REQUESTED** [review]
image

Hi Kam - can you move these files from the top level into the appropriate subfolder? ie `Presentations/Week02/Cohort2/`

**Comment by camcaan** [comment]
Hi
Sorry I think I messed up the whole repository. I am new to git but trying to sort this out.

Regards

Kamran KHAN
________________________________

**Comment by tanho63** [comment]
Hiya, yeah - looks like you might need a fresh start! Let me see if I can get a chance to make a little demo video for you sometime this afternoon.

**Comment by camcaan** [comment]
Hi
That will help greatly. I have read so much about GitHub and using it with R studio but I think I just got everything mixed up. But I think I have managed to got it right at the end but have duplicates things some of which might need deleting.

Kind regards
Kamran


Kamran KHAN
________________________________

**Comment by tanho63** [comment]
Heya @camcaan can you give this another go?

**Review by tanho63 — APPROVED** [review]

**Pull request merged**
